name: Tests
on: [push, pull_request]

jobs:
  build:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    steps:
    - name: Install Pre-requisits on ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++ ninja-build cmake
        ninja --version
        cmake --version
        g++ --version

    - name: Install dependencies on windows
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install ninja cmake
        ninja --version
        cmake --version

    - uses: actions/checkout@v2
    - name: cmake build
      run: |
        mkdir build
        cmake -Bbuild -S.
        cmake --build build/ --target hyperloglog_tests

    - name: Run tests
      if: startsWith(matrix.os, 'windows')
      run: build/Debug/hyperloglog_tests.exe

    - name: Run tests
      if: !startsWith(matrix.os, 'windows')
      run: build/hyperloglog_tests
