name: Tests
on: [push, pull_request]

jobs:
  build:
    name: ${ { matrix.config.name } }
    runs-on: ${ { matrix.config.os } }

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    steps:
    - name: Install Pre-requisits on ubuntu
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++ ninja-build cmake
        ninja --version
        cmake --version
        g++ --version

    - name: Install dependencies on windows
      if: startsWith(matrix.config.os, 'windows')
      run: |
        choco install ninja cmake
        ninja --version
        cmake --version

    - uses: actions/checkout@v2
    - name: cmake build
      run: |
        mkdir build
        cmake -Bbuild -H.
        cmake --build build/ --target hyperloglog_tests
    - name: Run tests
      run: build/hyperloglog_tests
